//! Build script for botster CLI.
//!
//! Three responsibilities:
//! 1. Embeds Lua files from `lua/` into the binary (release builds only).
//! 2. Builds libghostty-vt from `vendor/ghostty/` via Zig and links it.
//! 3. Compiles xterm-ghostty terminfo and embeds the result.
//!
//! Generated files in `$OUT_DIR/`:
//! - `embedded_lua.rs`: Array of (path, content) tuples + lookup function
//! - `embedded_terminfo.rs`: Array of (path, bytes) tuples for compiled terminfo

use std::env;
use std::fs::{self, File};
use std::io::Write;
#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;
use std::path::Path;
use std::process::Command;

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("embedded_lua.rs");
    let profile = env::var("PROFILE").unwrap_or_default();

    if profile == "release" {
        generate_embedded_lua(&dest_path);
    } else {
        generate_stub_lua(&dest_path);
    }

    compile_terminfo(&out_dir);
    build_ghostty_vt();
}

/// Generate embedded Lua module with all files inlined via include_str!().
/// Used for release builds so the binary is self-contained.
fn generate_embedded_lua(dest_path: &Path) {
    let lua_dir = Path::new("lua");

    // Collect all Lua files
    let mut lua_files: Vec<(String, String)> = Vec::new();
    if lua_dir.exists() {
        collect_lua_files(lua_dir, lua_dir, &mut lua_files);
    }

    // Sort for deterministic builds
    lua_files.sort_by(|a, b| a.0.cmp(&b.0));

    // Generate the Rust source
    let mut output = File::create(dest_path).unwrap();

    writeln!(output, "// Auto-generated by build.rs - do not edit").unwrap();
    writeln!(output, "// Embeds all Lua files from cli/lua/").unwrap();
    writeln!(output).unwrap();

    // Generate the array of embedded files
    writeln!(
        output,
        "pub static EMBEDDED_LUA_FILES: &[(&str, &str)] = &["
    )
    .unwrap();

    for (rel_path, abs_path) in &lua_files {
        // Use include_str! with the absolute path
        writeln!(
            output,
            "    (\"{}\", include_str!(\"{}\")),",
            rel_path, abs_path
        )
        .unwrap();
    }

    writeln!(output, "];").unwrap();
    writeln!(output).unwrap();

    // Generate the lookup function
    writeln!(
        output,
        "/// Get embedded Lua file content by relative path."
    )
    .unwrap();
    writeln!(output, "///").unwrap();
    writeln!(output, "/// # Arguments").unwrap();
    writeln!(output, "///").unwrap();
    writeln!(
        output,
        "/// * `path` - Relative path like \"core/init.lua\""
    )
    .unwrap();
    writeln!(output, "///").unwrap();
    writeln!(output, "/// # Returns").unwrap();
    writeln!(output, "///").unwrap();
    writeln!(output, "/// The file content if found, None otherwise.").unwrap();
    writeln!(output, "#[allow(dead_code)]").unwrap();
    writeln!(
        output,
        "pub fn get_embedded_lua(path: &str) -> Option<&'static str> {{"
    )
    .unwrap();
    writeln!(output, "    EMBEDDED_LUA_FILES").unwrap();
    writeln!(output, "        .iter()").unwrap();
    writeln!(output, "        .find(|(p, _)| *p == path)").unwrap();
    writeln!(output, "        .map(|(_, content)| *content)").unwrap();
    writeln!(output, "}}").unwrap();

    // Tell Cargo to rerun if any Lua file changes.
    //
    // cargo:rerun-if-changed on a directory only watches the directory's own
    // mtime, NOT files in subdirectories. We must watch each subdirectory
    // individually so that adding a new .lua file (which changes the parent
    // dir's mtime) triggers a rebuild.
    watch_lua_directory(&Path::new("lua"));

    // Also watch individual files for content changes
    for (_, abs_path) in &lua_files {
        println!("cargo:rerun-if-changed={}", abs_path);
    }
}

/// Generate stub embedded Lua module with empty array.
/// Used for debug builds — Lua files are loaded from the filesystem and
/// hot-reloaded, so embedding them would just cause unnecessary recompiles.
fn generate_stub_lua(dest_path: &Path) {
    let mut output = File::create(dest_path).unwrap();

    writeln!(output, "// Auto-generated by build.rs - do not edit").unwrap();
    writeln!(
        output,
        "// Debug build: Lua files loaded from filesystem, not embedded"
    )
    .unwrap();
    writeln!(output).unwrap();
    writeln!(
        output,
        "pub static EMBEDDED_LUA_FILES: &[(&str, &str)] = &[];"
    )
    .unwrap();
    writeln!(output).unwrap();
    writeln!(output, "#[allow(dead_code)]").unwrap();
    writeln!(
        output,
        "pub fn get_embedded_lua(_path: &str) -> Option<&'static str> {{"
    )
    .unwrap();
    writeln!(output, "    None").unwrap();
    writeln!(output, "}}").unwrap();

    // Only rerun if build.rs itself changes, NOT when Lua files change
    println!("cargo:rerun-if-changed=build.rs");
}

/// Recursively register `cargo:rerun-if-changed` for a directory and all
/// its subdirectories.
///
/// `cargo:rerun-if-changed` on a directory only detects changes to the
/// directory's own mtime (e.g., a file added/removed directly inside it).
/// Without watching subdirectories, adding `lua/lib/agent.lua` would only
/// change `lua/lib/`'s mtime — not `lua/`'s — so build.rs wouldn't re-run
/// and the new file would be missing from the embedded binary.
fn watch_lua_directory(dir: &Path) {
    println!("cargo:rerun-if-changed={}", dir.display());
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            if entry.path().is_dir() {
                watch_lua_directory(&entry.path());
            }
        }
    }
}

/// Compile the xterm-ghostty terminfo source with `tic` and generate
/// `embedded_terminfo.rs` containing the compiled entries as byte arrays.
///
/// If `tic` is not available, generates an empty array — the runtime module
/// will fall back to `xterm-256color`.
fn compile_terminfo(out_dir: &str) {
    let source = Path::new("assets/xterm-ghostty.terminfo");
    let terminfo_dir = Path::new(out_dir).join("terminfo");
    let dest_rs = Path::new(out_dir).join("embedded_terminfo.rs");

    println!("cargo:rerun-if-changed={}", source.display());

    // Try to compile with tic
    let compiled = if source.exists() {
        let _ = fs::create_dir_all(&terminfo_dir);
        match Command::new("tic")
            .args([
                "-x",
                "-o",
                &terminfo_dir.to_string_lossy(),
                &source.to_string_lossy(),
            ])
            .output()
        {
            Ok(output) if output.status.success() => {
                // Collect all compiled files
                let mut files = Vec::new();
                collect_terminfo_files(&terminfo_dir, &terminfo_dir, &mut files);
                files.sort();
                files
            }
            Ok(output) => {
                let stderr = String::from_utf8_lossy(&output.stderr);
                eprintln!("cargo:warning=tic failed ({}): {stderr}", output.status);
                Vec::new()
            }
            Err(e) => {
                eprintln!("cargo:warning=tic not available: {e} — terminfo will use xterm-256color fallback");
                Vec::new()
            }
        }
    } else {
        eprintln!("cargo:warning=assets/xterm-ghostty.terminfo not found");
        Vec::new()
    };

    // Generate the Rust source with include_bytes! for each compiled entry
    let mut out = File::create(&dest_rs).expect("create embedded_terminfo.rs");
    writeln!(out, "// Auto-generated by build.rs — do not edit").unwrap();
    writeln!(
        out,
        "/// Pre-compiled terminfo entries: (relative_path, compiled_bytes)."
    )
    .unwrap();
    writeln!(
        out,
        "pub static TERMINFO_FILES: &[(&str, &[u8])] = &["
    )
    .unwrap();
    for (rel_path, abs_path) in &compiled {
        writeln!(
            out,
            "    (\"{rel_path}\", include_bytes!(\"{abs_path}\")),",
        )
        .unwrap();
    }
    writeln!(out, "];").unwrap();
}

/// Recursively collect compiled terminfo files as (relative_path, absolute_path).
fn collect_terminfo_files(base: &Path, dir: &Path, files: &mut Vec<(String, String)>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_terminfo_files(base, &path, files);
        } else {
            let rel = path
                .strip_prefix(base)
                .unwrap()
                .to_string_lossy()
                .to_string();
            let abs = path.canonicalize().unwrap().to_string_lossy().to_string();
            files.push((rel, abs));
        }
    }
}

/// Build libghostty-vt from the vendored Ghostty source using Zig.
///
/// Runs `mise exec -- zig build -Demit-lib-vt` in `vendor/ghostty/` and tells
/// Cargo to link the resulting static library. Uses DEVELOPER_DIR to point at
/// the Command Line Tools SDK to work around a zig 0.15 + Xcode 26.4 TBD
/// architecture mismatch bug (Codeberg #31658).
fn build_ghostty_vt() {
    let ghostty_dir = Path::new("vendor/ghostty");
    let out_dir = env::var("OUT_DIR").unwrap();
    let repacked_lib = Path::new(&out_dir).join("libghostty-vt.a");
    let zig_lib_path = ghostty_dir.join("zig-out/lib/libghostty-vt.a");

    let zig_args = [
        "build",
        "-Demit-lib-vt",
        "-Doptimize=ReleaseFast",
        "-Dsimd=false",
        "-Dcpu=baseline",
    ];

    // Try mise first (local dev), fall back to bare zig (CI).
    let status = Command::new("mise")
        .args(["exec", "--", "zig"])
        .args(&zig_args)
        .current_dir(ghostty_dir)
        .env("DEVELOPER_DIR", "/Library/Developer/CommandLineTools")
        .status()
        .or_else(|_| {
            Command::new("zig")
                .args(&zig_args)
                .current_dir(ghostty_dir)
                .status()
        })
        .expect("failed to run zig build — is zig or mise installed?");

    assert!(
        status.success(),
        "zig build -Demit-lib-vt failed with exit code {:?}",
        status.code()
    );

    assert!(
        zig_lib_path.exists(),
        "zig build succeeded but {} not found",
        zig_lib_path.display()
    );

    // Zig's archive has misaligned members that macOS ld rejects
    // ("not 8-byte aligned"). Extract objects and repack with `ar` to
    // fix alignment. (libtool -static strips the main object with zig 0.15.)
    let tmp_dir = Path::new(&out_dir).join("ghostty-repack");
    let _ = std::fs::remove_dir_all(&tmp_dir);
    let _ = std::fs::create_dir_all(&tmp_dir);
    let _ = std::fs::remove_file(&repacked_lib);

    // Extract .o files from the zig archive (use canonical path since
    // current_dir is set to the temp extraction directory).
    let zig_lib_abs = std::fs::canonicalize(&zig_lib_path)
        .unwrap_or_else(|_| panic!("{} not found", zig_lib_path.display()));
    let status = Command::new("ar")
        .args(["x", &zig_lib_abs.to_string_lossy()])
        .current_dir(&tmp_dir)
        .status()
        .expect("failed to run `ar x`");
    assert!(status.success(), "ar x failed");

    // Collect all .o files and fix permissions (zig's ar extracts with 0000 mode)
    let mut objects: Vec<_> = std::fs::read_dir(&tmp_dir)
        .expect("read repack dir")
        .filter_map(|e| {
            let p = e.ok()?.path();
            if p.extension().is_some_and(|ext| ext == "o") {
                // Fix permissions — zig archives extract with mode 0000
                #[cfg(unix)]
                let _ = fs::set_permissions(&p, fs::Permissions::from_mode(0o644));
                Some(p)
            } else {
                None
            }
        })
        .collect();
    objects.sort();

    // Repack with ar (produces properly aligned archive)
    let mut ar_cmd = Command::new("ar");
    ar_cmd.args(["rcs"]).arg(&repacked_lib);
    for obj in &objects {
        ar_cmd.arg(obj);
    }
    let status = ar_cmd.status().expect("failed to run `ar rcs`");
    assert!(status.success(), "ar rcs repack failed");

    // Clean up temp dir
    let _ = std::fs::remove_dir_all(&tmp_dir);

    println!("cargo:rustc-link-search=native={}", out_dir);
    println!("cargo:rustc-link-lib=static=ghostty-vt");

    // libghostty-vt (without SIMD) only needs libc, which Rust links by default.
    // On macOS, also link the C++ runtime for Zig's compiler-rt.
    if cfg!(target_os = "macos") {
        println!("cargo:rustc-link-lib=c++");
    }

    // Rerun if ghostty source changes.
    println!("cargo:rerun-if-changed=vendor/ghostty/build.zig");
    println!("cargo:rerun-if-changed=vendor/ghostty/build.zig.zon");
    println!("cargo:rerun-if-changed=vendor/ghostty/src");
    println!("cargo:rerun-if-changed=vendor/ghostty/include");
}

/// Recursively collect all .lua files from a directory.
fn collect_lua_files(base: &Path, dir: &Path, files: &mut Vec<(String, String)>) {
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                collect_lua_files(base, &path, files);
            } else if path.extension().map_or(false, |ext| ext == "lua") {
                // Get relative path from base
                let rel_path = path
                    .strip_prefix(base)
                    .unwrap()
                    .to_string_lossy()
                    .to_string();
                // Get absolute path for include_str!
                let abs_path = path.canonicalize().unwrap().to_string_lossy().to_string();
                files.push((rel_path, abs_path));
            }
        }
    }
}
