//! Bundled terminfo for xterm-ghostty.
//!
//! The compiled terminfo database is embedded at build time (via `tic` in
//! `build.rs`).  At runtime this module writes the pre-compiled files to
//! `{data_dir}/terminfo/` — no external tools required on the target system.
//!
//! Spawned PTY processes get `TERM=xterm-ghostty` and `TERMINFO` pointing
//! at this directory.  If the build didn't have `tic` available, the module
//! falls back silently to `xterm-256color`.

use std::path::{Path, PathBuf};
use std::sync::OnceLock;

// Generated by build.rs — array of (relative_path, compiled_bytes) tuples.
include!(concat!(env!("OUT_DIR"), "/embedded_terminfo.rs"));

/// Cached result: `Some(dir)` when terminfo is installed, `None` on fallback.
static TERMINFO_DIR: OnceLock<Option<PathBuf>> = OnceLock::new();

/// Terminal configuration for spawned processes.
#[derive(Debug, Clone)]
pub struct TerminfoConfig {
    /// TERM value (e.g. `xterm-ghostty` or `xterm-256color`).
    pub term: String,
    /// Absolute path to the compiled terminfo database directory, if available.
    pub terminfo_dir: Option<String>,
}

/// Initialize the bundled terminfo database.
///
/// Idempotent: writes files only when the compiled output is missing.
/// Thread-safe via [`OnceLock`].  Call once during hub startup.
pub fn init(data_dir: &Path) -> TerminfoConfig {
    let dir = TERMINFO_DIR.get_or_init(|| {
        if TERMINFO_FILES.is_empty() {
            log::info!("Terminfo: no compiled entries embedded (tic unavailable at build time)");
            return None;
        }

        let terminfo_dir = data_dir.join("terminfo");
        if is_installed(&terminfo_dir) {
            return Some(terminfo_dir);
        }

        match install(&terminfo_dir) {
            Ok(()) => Some(terminfo_dir),
            Err(reason) => {
                log::info!("Terminfo: {reason}, falling back to xterm-256color");
                None
            }
        }
    });

    to_config(dir.as_ref())
}

/// Get the terminfo config without re-initializing.
/// Returns fallback if [`init`] was never called.
pub fn config() -> TerminfoConfig {
    to_config(TERMINFO_DIR.get().and_then(|o| o.as_ref()))
}

fn to_config(dir: Option<&PathBuf>) -> TerminfoConfig {
    match dir {
        Some(d) => TerminfoConfig {
            term: "xterm-ghostty".into(),
            terminfo_dir: Some(d.to_string_lossy().into_owned()),
        },
        None => TerminfoConfig {
            term: "xterm-256color".into(),
            terminfo_dir: None,
        },
    }
}

/// Check whether the compiled terminfo is already installed on disk.
fn is_installed(terminfo_dir: &Path) -> bool {
    // Verify ALL embedded files exist — catches partial installs from
    // interrupted writes or version upgrades.
    TERMINFO_FILES
        .iter()
        .all(|(rel, _)| terminfo_dir.join(rel).exists())
}

/// Write all pre-compiled terminfo files to disk.
fn install(terminfo_dir: &Path) -> Result<(), String> {
    for &(rel_path, data) in TERMINFO_FILES {
        let dest = terminfo_dir.join(rel_path);
        if let Some(parent) = dest.parent() {
            std::fs::create_dir_all(parent)
                .map_err(|e| format!("cannot create {}: {e}", parent.display()))?;
        }
        std::fs::write(&dest, data)
            .map_err(|e| format!("cannot write {}: {e}", dest.display()))?;
    }

    log::info!(
        "Terminfo: installed {} entries to {}",
        TERMINFO_FILES.len(),
        terminfo_dir.display()
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn embedded_files_are_present() {
        // build.rs should have compiled terminfo if tic was available.
        // On CI this will always be true; locally it depends on ncurses.
        if TERMINFO_FILES.is_empty() {
            eprintln!("warning: TERMINFO_FILES empty — tic not available at build time");
            return;
        }
        // Every entry should have non-empty data
        for (path, data) in TERMINFO_FILES {
            assert!(!path.is_empty(), "empty path in TERMINFO_FILES");
            assert!(!data.is_empty(), "empty data for {path}");
        }
    }

    #[test]
    fn config_returns_valid_term() {
        let c = config();
        assert!(c.term == "xterm-ghostty" || c.term == "xterm-256color");
    }
}
